### ISSUE TITLE
Error Linking to Miele

### ISSUE THREAD

**Issue by schford** [docbobo/home-assistant-miele#4]
I think Miele is expecting an additional variable to be passed. IF you follow instructions on Mieles site you get.....

"Something went wrong when attempting authenticating with Miele@home. The error encountered was (missing_token) Missing access token parameter.. Please try again!"

**Comment by docbobo** [comment]
Is this upon initial configuration? Or at a later point in time?

**Comment by schford** [comment]
Initial configuration.

**Comment by schford** [comment]
This from Home Assistant Error Log
*****

Log Details (ERROR)
Tue Feb 05 2019 15:22:27 GMT+0000 (Greenwich Mean Time)

Missing token: (missing_token) Missing access token parameter.

**Comment by docbobo** [comment]
I think I've fixed the problem. Do you mind updating and giving it another try?

**Comment by schford** [comment]
will do! Doing it now

**Comment by schford** [comment]
fixed - Miele@home has been successfully authorized! You can close this window now!!

**Comment by docbobo** [comment]
Great to hear. Let's close this issue then ;)
